const USER_LOGGED_IN = "USER_LOGGED_OUT";
const USER_LOGGED_OUT = "USER_LOGGED_IN";
const CHANGE_ACTIVE_PAGE = "CHANGE_ACTIVE_PAGE";
const CHANGE_DIETARY_PREFERENCE = "CHANGE_DIETARY_PREFERENCE";
const ADD_EXPERIENCE_POINTS = "ADD_EXPERIENCE POINTS";
const USER_COMPLETED_RECIPE = "USER_COMPLETED_RECIPE";
const CHANGE_MEAT_PREFERENCE = "CHANGE_MEAT_PREFERENCE";
const CHANGE_ALLERGY = "CHANGE_ALLERGY";

export {
  USER_LOGGED_IN,
  USER_LOGGED_OUT,
  CHANGE_ACTIVE_PAGE,
  CHANGE_DIETARY_PREFERENCE,
  ADD_EXPERIENCE_POINTS,
  USER_COMPLETED_RECIPE,
  CHANGE_MEAT_PREFERENCE,
  CHANGE_ALLERGY,
};
