const USER_LOGGED_IN = "USER_LOGGED_OUT";
const USER_LOGGED_OUT = "USER_LOGGED_IN";
const CHANGE_ACTIVE_PAGE = "CHANGE_ACTIVE_PAGE";
const CHANGE_DIETARY_PREFERENCE = "CHANGE_DIETARY_PREFERENCE";

export {
  USER_LOGGED_IN,
  USER_LOGGED_OUT,
  CHANGE_ACTIVE_PAGE,
  CHANGE_DIETARY_PREFERENCE,
};
